controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login:
    path: /login
    controller: App\Controller\LoginController::index

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

main:
    path: /
    controller: App\Controller\MainController::index

app_linklist:
    path: /linklist
    controller: App\Controller\LinkListController::index

app_userlist:
    path: /userlist
    controller: App\Controller\UserListController::index

app_manageaccount:
    path: /manageaccount
    controller: App\Controller\ManageAccountController::index

app_generate:
    path: /generate
    controller: App\Controller\GenerateController::index